name: Docker

on:
  push:
    branches:
      - main
env:
  REGISTRY: docker.io
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[docker-build]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare ignores
        run: mv -f Dockerfile.base.dockerignore .dockerignore
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@1cce1654e01caa87cc0eac1c100e6749708affb9
        with:
          registry: ${{ env.REGISTRY }}
          username: geopjr
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@b1aeb1103e6b3b5648dbd6deaf0559919456ca6b
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            geopjr/co2-node-chromium-pnpm:stable
